# coding: utf-8

"""
    Loopy Loyalty API

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0
    Contact: support@loopyloyalty.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.locations_beacons_api import LocationsBeaconsApi


class TestLocationsBeaconsApi(unittest.TestCase):
    """ LocationsBeaconsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.locations_beacons_api.LocationsBeaconsApi()

    def tearDown(self):
        pass

    def test_loopy_loyalty_create_beacon(self):
        """
        Test case for loopy_loyalty_create_beacon

        Create beacon
        """
        pass

    def test_loopy_loyalty_create_location(self):
        """
        Test case for loopy_loyalty_create_location

        Create location
        """
        pass

    def test_loopy_loyalty_delete_beacon(self):
        """
        Test case for loopy_loyalty_delete_beacon

        Delete beacon
        """
        pass

    def test_loopy_loyalty_delete_location(self):
        """
        Test case for loopy_loyalty_delete_location

        Delete location
        """
        pass

    def test_loopy_loyalty_get_beacon(self):
        """
        Test case for loopy_loyalty_get_beacon

        Get beacon
        """
        pass

    def test_loopy_loyalty_get_location(self):
        """
        Test case for loopy_loyalty_get_location

        Get location
        """
        pass

    def test_loopy_loyalty_list_beacons(self):
        """
        Test case for loopy_loyalty_list_beacons

        List beacons
        """
        pass

    def test_loopy_loyalty_list_locations(self):
        """
        Test case for loopy_loyalty_list_locations

        List locations
        """
        pass

    def test_loopy_loyalty_update_beacon(self):
        """
        Test case for loopy_loyalty_update_beacon

        Update beacon
        """
        pass

    def test_loopy_loyalty_update_location(self):
        """
        Test case for loopy_loyalty_update_location

        Update location
        """
        pass


if __name__ == '__main__':
    unittest.main()
