# coding: utf-8

"""
    Loopy Loyalty API

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0
    Contact: support@loopyloyalty.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.subusers_api import SubusersApi


class TestSubusersApi(unittest.TestCase):
    """ SubusersApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.subusers_api.SubusersApi()

    def tearDown(self):
        pass

    def test_loopy_loyalty_create_subuser(self):
        """
        Test case for loopy_loyalty_create_subuser

        Create subuser
        """
        pass

    def test_loopy_loyalty_delete_subuser(self):
        """
        Test case for loopy_loyalty_delete_subuser

        Delete subuser
        """
        pass

    def test_loopy_loyalty_get_subuser(self):
        """
        Test case for loopy_loyalty_get_subuser

        Gets subuser
        """
        pass

    def test_loopy_loyalty_list_sub_users(self):
        """
        Test case for loopy_loyalty_list_sub_users

        List subusers
        """
        pass

    def test_loopy_loyalty_update_subuser(self):
        """
        Test case for loopy_loyalty_update_subuser

        Update subuser
        """
        pass


if __name__ == '__main__':
    unittest.main()
