# coding: utf-8

"""
    Loopy Loyalty API

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0
    Contact: support@loopyloyalty.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.cards_api import CardsApi


class TestCardsApi(unittest.TestCase):
    """ CardsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.cards_api.CardsApi()

    def tearDown(self):
        pass

    def test_loopy_loyalty_delete_card(self):
        """
        Test case for loopy_loyalty_delete_card

        Delete card (by ID)
        """
        pass

    def test_loopy_loyalty_get_card_by_id(self):
        """
        Test case for loopy_loyalty_get_card_by_id

        Get card (by ID)
        """
        pass

    def test_loopy_loyalty_get_card_by_unique_id(self):
        """
        Test case for loopy_loyalty_get_card_by_unique_id

        Get card (by unique ID)
        """
        pass

    def test_loopy_loyalty_list_cards(self):
        """
        Test case for loopy_loyalty_list_cards

        List cards
        """
        pass

    def test_loopy_loyalty_resync_card(self):
        """
        Test case for loopy_loyalty_resync_card

        Re-sync card
        """
        pass

    def test_loopy_loyalty_send_message_to_all_cards(self):
        """
        Test case for loopy_loyalty_send_message_to_all_cards

        Send message to all cards
        """
        pass

    def test_loopy_loyalty_send_message_to_individual_card(self):
        """
        Test case for loopy_loyalty_send_message_to_individual_card

        Send message to an individual card
        """
        pass


if __name__ == '__main__':
    unittest.main()
