# coding: utf-8

"""
    Loopy Loyalty API

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0
    Contact: support@loopyloyalty.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

# import models into sdk package
from .models.googlerpc_status import GooglerpcStatus
from .models.io_id import IoId
from .models.loopy_add_stamps_request import LoopyAddStampsRequest
from .models.loopy_add_stamps_with_unique_id_request import LoopyAddStampsWithUniqueIdRequest
from .models.loopy_beacon import LoopyBeacon
from .models.loopy_business import LoopyBusiness
from .models.loopy_campaign import LoopyCampaign
from .models.loopy_campaign_exists_response import LoopyCampaignExistsResponse
from .models.loopy_campaign_export_request import LoopyCampaignExportRequest
from .models.loopy_campaign_for_list import LoopyCampaignForList
from .models.loopy_campaign_public import LoopyCampaignPublic
from .models.loopy_campaign_type import LoopyCampaignType
from .models.loopy_card import LoopyCard
from .models.loopy_card_unique_ids import LoopyCardUniqueIds
from .models.loopy_create_image_asset_request import LoopyCreateImageAssetRequest
from .models.loopy_create_image_asset_response import LoopyCreateImageAssetResponse
from .models.loopy_custom_front_field import LoopyCustomFrontField
from .models.loopy_data_field import LoopyDataField
from .models.loopy_data_field_type import LoopyDataFieldType
from .models.loopy_design import LoopyDesign
from .models.loopy_enrol_customer_request import LoopyEnrolCustomerRequest
from .models.loopy_enrol_customer_response import LoopyEnrolCustomerResponse
from .models.loopy_event import LoopyEvent
from .models.loopy_expiry import LoopyExpiry
from .models.loopy_export_segment import LoopyExportSegment
from .models.loopy_filter_condition import LoopyFilterCondition
from .models.loopy_get_card_response import LoopyGetCardResponse
from .models.loopy_get_image_response import LoopyGetImageResponse
from .models.loopy_get_strip_image_template_response import LoopyGetStripImageTemplateResponse
from .models.loopy_ip import LoopyIP
from .models.loopy_image_asset_type import LoopyImageAssetType
from .models.loopy_image_type import LoopyImageType
from .models.loopy_individual_message_request import LoopyIndividualMessageRequest
from .models.loopy_link import LoopyLink
from .models.loopy_list_beacons_response import LoopyListBeaconsResponse
from .models.loopy_list_beacons_row import LoopyListBeaconsRow
from .models.loopy_list_campaigns_response import LoopyListCampaignsResponse
from .models.loopy_list_campaigns_row import LoopyListCampaignsRow
from .models.loopy_list_cards_column import LoopyListCardsColumn
from .models.loopy_list_cards_data_table_input import LoopyListCardsDataTableInput
from .models.loopy_list_cards_data_table_output import LoopyListCardsDataTableOutput
from .models.loopy_list_cards_order import LoopyListCardsOrder
from .models.loopy_list_cards_request import LoopyListCardsRequest
from .models.loopy_list_events_data_table_input import LoopyListEventsDataTableInput
from .models.loopy_list_events_data_table_output import LoopyListEventsDataTableOutput
from .models.loopy_list_events_order import LoopyListEventsOrder
from .models.loopy_list_events_request import LoopyListEventsRequest
from .models.loopy_list_locations_response import LoopyListLocationsResponse
from .models.loopy_list_locations_row import LoopyListLocationsRow
from .models.loopy_list_stamp_images_response import LoopyListStampImagesResponse
from .models.loopy_list_subusers_response import LoopyListSubusersResponse
from .models.loopy_list_subusers_row import LoopyListSubusersRow
from .models.loopy_location import LoopyLocation
from .models.loopy_my_sql_event import LoopyMySqlEvent
from .models.loopy_my_sql_transaction import LoopyMySqlTransaction
from .models.loopy_pass_type import LoopyPassType
from .models.loopy_redeem_rewards_request import LoopyRedeemRewardsRequest
from .models.loopy_redeem_rewards_with_unique_id_request import LoopyRedeemRewardsWithUniqueIdRequest
from .models.loopy_request_meta_data import LoopyRequestMetaData
from .models.loopy_resync_card_request import LoopyResyncCardRequest
from .models.loopy_reward import LoopyReward
from .models.loopy_send_message_request import LoopySendMessageRequest
from .models.loopy_status import LoopyStatus
from .models.loopy_strip_image import LoopyStripImage
from .models.loopy_subscription_event_type import LoopySubscriptionEventType
from .models.loopy_subscription_request import LoopySubscriptionRequest
from .models.loopy_subuser import LoopySubuser
from .models.loopy_success_response import LoopySuccessResponse
from .models.loopy_update_beacon_response import LoopyUpdateBeaconResponse
from .models.loopy_update_location_response import LoopyUpdateLocationResponse
from .models.protobuf_any import ProtobufAny

# import apis into sdk package
from .apis.campaigns_api import CampaignsApi
from .apis.cards_api import CardsApi
from .apis.enrolment_api import EnrolmentApi
from .apis.images_api import ImagesApi
from .apis.locations_beacons_api import LocationsBeaconsApi
from .apis.reporting_api import ReportingApi
from .apis.stamps_rewards_api import StampsRewardsApi
from .apis.subusers_api import SubusersApi
from .apis.webhook_subscriptions_api import WebhookSubscriptionsApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
