# coding: utf-8

"""
    Loopy Loyalty API

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0
    Contact: support@loopyloyalty.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class LoopyRequestMetaData(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, ip=None, referrer=None, user_agent=None):
        """
        LoopyRequestMetaData - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'ip': 'LoopyIP',
            'referrer': 'str',
            'user_agent': 'str'
        }

        self.attribute_map = {
            'ip': 'ip',
            'referrer': 'referrer',
            'user_agent': 'userAgent'
        }

        self._ip = ip
        self._referrer = referrer
        self._user_agent = user_agent

    @property
    def ip(self):
        """
        Gets the ip of this LoopyRequestMetaData.
        IP address details.

        :return: The ip of this LoopyRequestMetaData.
        :rtype: LoopyIP
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """
        Sets the ip of this LoopyRequestMetaData.
        IP address details.

        :param ip: The ip of this LoopyRequestMetaData.
        :type: LoopyIP
        """

        self._ip = ip

    @property
    def referrer(self):
        """
        Gets the referrer of this LoopyRequestMetaData.
        Referrer details.

        :return: The referrer of this LoopyRequestMetaData.
        :rtype: str
        """
        return self._referrer

    @referrer.setter
    def referrer(self, referrer):
        """
        Sets the referrer of this LoopyRequestMetaData.
        Referrer details.

        :param referrer: The referrer of this LoopyRequestMetaData.
        :type: str
        """

        self._referrer = referrer

    @property
    def user_agent(self):
        """
        Gets the user_agent of this LoopyRequestMetaData.
        User agent details.

        :return: The user_agent of this LoopyRequestMetaData.
        :rtype: str
        """
        return self._user_agent

    @user_agent.setter
    def user_agent(self, user_agent):
        """
        Sets the user_agent of this LoopyRequestMetaData.
        User agent details.

        :param user_agent: The user_agent of this LoopyRequestMetaData.
        :type: str
        """

        self._user_agent = user_agent

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
