# coding: utf-8

"""
    Loopy Loyalty API

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0
    Contact: support@loopyloyalty.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class LoopyCreateImageAssetRequest(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, base64_string=None, type=None, opacity=None):
        """
        LoopyCreateImageAssetRequest - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'base64_string': 'str',
            'type': 'LoopyImageAssetType',
            'opacity': 'int'
        }

        self.attribute_map = {
            'base64_string': 'base64String',
            'type': 'type',
            'opacity': 'opacity'
        }

        self._base64_string = base64_string
        self._type = type
        self._opacity = opacity

    @property
    def base64_string(self):
        """
        Gets the base64_string of this LoopyCreateImageAssetRequest.
        Base64 encoded image string.

        :return: The base64_string of this LoopyCreateImageAssetRequest.
        :rtype: str
        """
        return self._base64_string

    @base64_string.setter
    def base64_string(self, base64_string):
        """
        Sets the base64_string of this LoopyCreateImageAssetRequest.
        Base64 encoded image string.

        :param base64_string: The base64_string of this LoopyCreateImageAssetRequest.
        :type: str
        """

        self._base64_string = base64_string

    @property
    def type(self):
        """
        Gets the type of this LoopyCreateImageAssetRequest.
        The image type.

        :return: The type of this LoopyCreateImageAssetRequest.
        :rtype: LoopyImageAssetType
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this LoopyCreateImageAssetRequest.
        The image type.

        :param type: The type of this LoopyCreateImageAssetRequest.
        :type: LoopyImageAssetType
        """

        self._type = type

    @property
    def opacity(self):
        """
        Gets the opacity of this LoopyCreateImageAssetRequest.
        The image opacity (0-100).

        :return: The opacity of this LoopyCreateImageAssetRequest.
        :rtype: int
        """
        return self._opacity

    @opacity.setter
    def opacity(self, opacity):
        """
        Sets the opacity of this LoopyCreateImageAssetRequest.
        The image opacity (0-100).

        :param opacity: The opacity of this LoopyCreateImageAssetRequest.
        :type: int
        """

        self._opacity = opacity

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
