# coding: utf-8

"""
    Loopy Loyalty API

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0
    Contact: support@loopyloyalty.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class LoopyGetCardResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, card=None, events=None, rewards=None):
        """
        LoopyGetCardResponse - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'card': 'LoopyCard',
            'events': 'list[LoopyMySqlTransaction]',
            'rewards': 'list[LoopyReward]'
        }

        self.attribute_map = {
            'card': 'card',
            'events': 'events',
            'rewards': 'rewards'
        }

        self._card = card
        self._events = events
        self._rewards = rewards

    @property
    def card(self):
        """
        Gets the card of this LoopyGetCardResponse.


        :return: The card of this LoopyGetCardResponse.
        :rtype: LoopyCard
        """
        return self._card

    @card.setter
    def card(self, card):
        """
        Sets the card of this LoopyGetCardResponse.


        :param card: The card of this LoopyGetCardResponse.
        :type: LoopyCard
        """

        self._card = card

    @property
    def events(self):
        """
        Gets the events of this LoopyGetCardResponse.


        :return: The events of this LoopyGetCardResponse.
        :rtype: list[LoopyMySqlTransaction]
        """
        return self._events

    @events.setter
    def events(self, events):
        """
        Sets the events of this LoopyGetCardResponse.


        :param events: The events of this LoopyGetCardResponse.
        :type: list[LoopyMySqlTransaction]
        """

        self._events = events

    @property
    def rewards(self):
        """
        Gets the rewards of this LoopyGetCardResponse.


        :return: The rewards of this LoopyGetCardResponse.
        :rtype: list[LoopyReward]
        """
        return self._rewards

    @rewards.setter
    def rewards(self, rewards):
        """
        Sets the rewards of this LoopyGetCardResponse.


        :param rewards: The rewards of this LoopyGetCardResponse.
        :type: list[LoopyReward]
        """

        self._rewards = rewards

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
